name: Update GeoIP Database

on:
  schedule:
    - cron: '30 */1 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  issues: write

jobs:
  update-geoip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download GeoIP
        run: |
          mkdir -p GeoIP
          echo "Downloading GeoIP database..."
          curl -s https://mailfud.org/geoip-legacy/GeoIP.dat.gz -o GeoIP/GeoIP.dat.gz

          if [ -f "GeoIP/GeoIP.dat.gz" ]; then
            echo "Download complete..."
          else
            echo "gDownload failed"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          echo "Checking for changes..."
          if git status | grep -q "GeoIP/"; then
            echo "Changes detected, committing..."
            git add GeoIP/
            git commit -m "Update GeoIP database [automated]"
            git push
            echo "Changes pushed successfully"
          else
            echo "No changes to commit"
          fi